server:
  port: ${PORT:8080}
  servlet:
    context-path: /v1

spring:
  application:
    name: async-buffer
  profiles:
    active: ${PROFILE_ACTIVE:dev}

  datasource:
    batch:
      name: batch
      username: root
      password: secret
      url: "jdbc:mariadb://localhost:3310/batch"
      driver-class-name: org.mariadb.jdbc.Driver

    buffer:
      name: batch
      username: root
      password: secret
      url: "jdbc:mariadb://localhost:3310/buffer"
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    open-in-view: true

  batch:
    job:
      enabled: false
    jdbc:
      table-prefix: TB_BATCH_
      initialize-schema: never

  flyway:
    driver-class-name: org.mariadb.jdbc.Driver
    default-schema: flyway
    create-schemas: true
    baseline-on-migrate: true
    schemas: flyway
    url: "jdbc:mariadb://localhost:3310/flyway"
    user: root
    password: secret
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    path: /docs/openipa

buffer:
  root:
    path: ${ROOT_PATH:/home/lelton/tmp/buffer}

