services:
  db_batch:
    image: mariadb:10.10.3
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: flyway
    volumes:
      - ./src/docker/:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"
    networks:
      - net-batch

networks:
  net-batch:
    name: net-batch
    driver: bridge