drop schema buffer;

create schema if not exists buffer collate utf8_bin;

CREATE SEQUENCE `buffer`.SEQ_TB_PERSON START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=INNODB;
CREATE SEQUENCE `buffer`.SEQ_TB_TYPE_DOCUMENT START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775806 INCREMENT BY 1 NOCACHE NOCYCLE ENGINE=INNODB;

CREATE TABLE `buffer`.TB_TYPE_DOCUMENT
(
    SEQ_TYPE_DOCUMENT BIGINT DEFAULT NEXTVAL(`buffer`.`SEQ_TB_TYPE_DOCUMENT`) NOT NULL PRIMARY KEY,
    CD_TYPE           INT(1) NOT NULL COMMENT 'TYPE OF PERSON''S DUCUMENT',
    DS_DESCRIPTION    VARCHAR(20)  NOT NULL COMMENT 'DESCRIPTION DUCUMENT TYPE PERSON'
) COMMENT 'DOMAIN TABLE FOR PEOPLE DUCUMENT TYPES' ENGINE=InnoDB;

CREATE TABLE `buffer`.TB_PERSON
(
    SEQ_PERSON       BIGINT DEFAULT NEXTVAL(`buffer`.`SEQ_TB_PERSON`) NOT NULL PRIMARY KEY,
    VL_NAME          VARCHAR(255) NOT NULL COMMENT 'PERSON''S NAME',
    VL_DOCUMENT      VARCHAR(20)  NOT NULL COMMENT 'PERSON''S DOCUMENT',
    CD_TYPE_DOCUMENT BIGINT       NOT NULL COMMENT 'PERSON''S DOCUMENT TYPE',
    CD_AGE           INT          NOT NULL COMMENT 'PERSON''S AGE',
    CONSTRAINT FK_TYPE_DOC FOREIGN KEY (CD_TYPE_DOCUMENT) REFERENCES `buffer`.TB_TYPE_DOCUMENT (SEQ_TYPE_DOCUMENT)
) COMMENT 'PERSON TABLE' ENGINE=InnoDB;

CREATE TABLE `buffer`.TB_USER_LOGIN
(
    CD_SEQ_PERSON       BIGINT                         NOT NULL COMMENT 'PK TABLE PERSON',
    VL_LOGIN            VARCHAR(255)                   NOT NULL COMMENT 'LOGIN USER',
    VL_PASSWORD         VARCHAR(255)                   NOT NULL COMMENT 'PASSWORD USER',
    DT_LAST_UPDATE_PASS DATE COMMENT 'DATE OF LAST PASSWORD UPDATE',
    DT_LAST_ACCESS      DATE COMMENT 'LAST ACCESS DATE',
    DT_CREATED_AT       DATE DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'DATE OF CREATION OF THE REGISTRATION',
    CONSTRAINT PK_USER_LOGIN PRIMARY KEY(CD_SEQ_PERSON),
    CONSTRAINT FK_TB_PERSON FOREIGN KEY (CD_SEQ_PERSON) REFERENCES `buffer`.TB_PERSON (SEQ_PERSON)
) COMMENT 'USER LOGIN TABLE' ENGINE=InnoDB;